name: Update works

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'
    - name: checkout aozorabunko source
      run: git clone --depth 1 https://github.com/aozorabunko/aozorabunko.git
    - name: extract txt from zips
      run: go run ./cmd/extzip -src aozorabunko -dest .
    - name: commit & push
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add --all cards
        git commit -m "[ci skip] update texts $(date '+%Y%m%d')" || echo "nothing to commit"
        git push origin HEAD:master
